export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const ADD_NOTE_TO_DATE = "ADD_NOTE_TO_DATE";
export const REMOVE_NOTE_FROM_STATE = "REMOVE_NOTE_FROM_STATE";
export const ADD_ERROR_TO_MODAL = "ADD_ERROR_TO_MODAL";
export const REMOVE_ERROR_FROM_MODAL = "REMOVE_ERROR_FROM_MODAL";
